name: Releases

on:
  workflow_dispatch:
  push:
    branches:
      - dev-next-chizi-0618

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_quic,with_dhcp,with_gvisor,with_utls,with_clash_api,with_provider

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev-net-chizi-0618
          fetch-depth: 0

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28
          add-to-path: false
          local-cache: false

      - name: Build core (Windows & Android & Linux)
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang

          # Windows build
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows GOAMD64=v3 make build

          # Android build
          CGO_ENABLED=1 CC=${CC} GOARCH=arm64 GOOS=android make build

          # Linux build and compress
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -v -trimpath -ldflags "-s -w -buildid=" -tags ${TAGS} -o CrashCore ./cmd/sing-box
          tar -czvf CrashCore.tar.gz CrashCore

      - name: Upload Linux
        uses: actions/upload-artifact@v4.3.1
        with:
          name: sing-box_linux
          path: CrashCore.tar.gz

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            sing-box*.exe
            sing-box
            CrashCore.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
