name: Fork Sync

on:
  schedule:
  - cron:  "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-sagernet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/SagerNet/sing-box.git"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.WORKFLOW_TOKEN }

  sync-chizi-0618:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/CHIZI-0618/sing-box.git"
        source_branch: "dev-next"
        destination_branch: "dev-next-chizi-0618"
        sync_tags: "false"
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
